---
title: "Create Joined PIN Level Data for each Tax Year"
author: "AWM"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, warning=FALSE, message=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(data.table)
library(ptaxsim)
library(glue)
library(DBI)

```

# Bring in data
```{r}
nicknames <- readxl::read_excel("./Necessary_Files/muni_shortnames.xlsx") %>%
  mutate(agency_number = as.character(agency_number),
         agency_number = str_pad(string = agency_number, width = 9, side = "left", pad ="0"))

ptaxsim_db_conn <- DBI::dbConnect(RSQLite::SQLite(), "./ptaxsim.db/ptaxsim-2023.0.0.db")

years <-(2021)

cross_county_lines <- c("030440000", "030585000", "030890000", "030320000", "031280000",
                        "030080000", "030560000", "031120000", "030280000", "030340000",
                        "030150000","030050000", "030180000","030500000", "031210000")

incentive_majorclasses <- c("6", "7A", "7B", "8A", "8B")


commercial_classes <- c(401:435, 490, 491, 492, 496:499,
                        500:535,590, 591, 592, 597:599,
                        700:799,
                        800:835, 891, 892, 897, 899)   %>% as.character()

industrial_classes <- c(480:489,493,
                        550:589, 593,
                        600:699,
                        850:890, 893 ) %>% as.character()



is.integer64 <- function(x){
  class(x)=="integer64"
}

```


```{r}
for(i in years){
  
  year_variable = i
  
  # PTAXSIM tables ---------------------------------------
  
  ## Municipality taxing agencies only + Cicero
  muni_agency_names <- DBI::dbGetQuery(
    ptaxsim_db_conn,
    "SELECT DISTINCT agency_num, agency_name, minor_type
    FROM agency_info
    WHERE minor_type = 'MUNI'
    OR agency_num = '020060000'
    "
  )
  
  
  agency_dt<- dbGetQuery(ptaxsim_db_conn, paste('SELECT * FROM agency WHERE year = ', i, ';'))
  agency_dt <- agency_dt %>%  mutate_if(is.integer64, as.double)
  
  tax_codes <- dbGetQuery(ptaxsim_db_conn, paste('SELECT DISTINCT tax_code_num, tax_code_rate FROM tax_code WHERE year = ', i, ';'))  

  
  
  
  sql <- "SELECT * FROM tax_code WHERE agency_num IN ({muni_agency_names$agency_num*}) AND year = ?year"
  query <- sqlInterpolate(ptaxsim_db_conn, sql, year = i)
  muni_tax_codes<- dbGetQuery(ptaxsim_db_conn, glue_sql(query, .con = ptaxsim_db_conn)) |> 
    select(-year)
  
  tif_distrib <- DBI::dbGetQuery(ptaxsim_db_conn, paste('SELECT * FROM tif_distribution WHERE year = ', i, ';')) 
  
  tif_distrib <- tif_distrib %>%
    select(tax_code_num, tax_code_distribution_pct) %>%
    mutate(tax_code_distribution_pct = tax_code_distribution_pct/100)
  
  
  ## All tax codes.
  ## tax codes within municipalities have additional info
  tc_muninames <- tax_codes %>%
    left_join(muni_tax_codes, by = c("tax_code_num", "tax_code_rate")) %>%
    left_join(muni_agency_names, by = "agency_num") %>%
    select(-agency_rate) %>%
    left_join(nicknames, by = c("agency_num" = "agency_number"))  |>   
    mutate(tax_code_rate = tax_code_rate/100)#%>% select(-c(minor_type, short_name, agency_number))
  
  
# PIN data from pin datatable in PTaxSim. Has exemption values and assessment values

sql <- "SELECT * FROM pin WHERE year = ?year"
query <- sqlInterpolate(ptaxsim_db_conn, sql, year = i)
pin_data <- dbGetQuery(ptaxsim_db_conn, glue_sql(query, .con = ptaxsim_db_conn))


  # combine taxing agency names and agency type to data table that has eav and extension values
  agency_data <- right_join(agency_dt, muni_agency_names) %>%
    select(-c(cty_dupage_eav:cty_livingston_eav)) %>% # drop some of the unused variables
    arrange(agency_num)
  
  
  eq_factor <- read_csv("./Necessary_Files/eq_factor.csv") %>%
    filter(year == i) %>%
    select(eq_factor_final) %>%
    as.numeric()
  
  ccao_loa <- read_csv("./inputs/ccao_loa.csv") %>%
    mutate(class_code = as.character(class_code)) %>%
    filter(year == i) %>%
    select(-year) %>%
    mutate(loa = as.numeric(loa)) %>%
    mutate(loa = ifelse(loa == 0, NA, loa))
  




# Exemptions at PIN level --------------------------------------------------


# finds all pins within Cook county and data on their exemptions
# joins tax code variable by pin

pin_data <- pin_data |>
  mutate_if(is.integer64, as.double ) %>%
  left_join(ccao_loa, by = c("class" = "class_code")) %>%
  left_join(tif_distrib, by ="tax_code_num") |>
    left_join(tc_muninames, by = c("tax_code_num")) |>

  
   mutate(
    incent_prop = ifelse(between(class, 600, 899), 1, 0),
    res_prop = ifelse(between(class, 200, 399), 1, 0),
    c2_prop = ifelse(between(class, 200, 299), 1, 0),
    
    # for A and B property types of commercial and industrial properties
    class_1dig = str_sub(class, 1, 1),
    class_group = case_when(
      (class_1dig == 5 & class %in% commercial_classes) ~ "5A",
      (class_1dig == 5 & class %in% industrial_classes) ~ "5B",
      class_1dig == 7 &  class < 742 ~ "7A",
      class_1dig == 7 &  class >= 742 ~ "7B",
      (class_1dig == 8 & class %in% commercial_classes ) ~ "8A",
      (class_1dig == 8 & class %in% industrial_classes ) ~ "8B",
      TRUE ~ as.character(class_1dig))) %>%
  
  # left_join(taxcode_rates, by = c("year", "tax_code_num")) |>
  mutate(zero_bill = ifelse(tax_bill_total == 0, 1, 0)) |>
  mutate(eq_av = av_clerk*eq_factor) |>
  mutate(exe_total = rowSums(across(starts_with("exe_"))),
         exe_total = ifelse(exe_total > eq_av, eq_av, exe_total)) |>
  mutate(taxable_eav = eq_av - exe_total) |>
  mutate(flag_missingdata = ifelse(taxable_eav > 1000 & tax_bill_total == 0 & c2_prop == 1, 1, 0)) |>
  mutate(exe_missing_disvet = ifelse(taxable_eav > 1000 & tax_bill_total == 0 & c2_prop == 1, taxable_eav, 0)) |>
  mutate(taxable_eav_adj = ifelse(taxable_eav > 1000 & flag_missingdata == 1, 0 , taxable_eav)) |>
  mutate(exe_total_adj = rowSums(across(starts_with("exe_")))- exe_total) # don't double count the total value when summing the values

  
pin_data <- pin_data |>
  mutate(all_exemptions = exe_homeowner + exe_senior + exe_freeze + exe_longtime_homeowner +
           exe_disabled + exe_vet_returning + exe_vet_dis_lt50 + exe_vet_dis_50_69 + exe_vet_dis_ge70 ,
         
         abatements = exe_abate, #abatements get their own variable
         fmv = av_clerk / loa,
         fmv = ifelse(is.na(fmv), 0, fmv)) %>%
  
  # Create binary variables for exemptions
  
  mutate(# zero_bill = ifelse(eav <= all_exemptions, 1, 0),  ## old way of creating zero bill but has missing vet exemptions data problem
    has_HO_exemp = ifelse(exe_homeowner > 0, 1, 0),
    has_SF_exemp = ifelse(exe_senior > 0, 1, 0),
    has_FR_exemp = ifelse(exe_freeze > 0, 1, 0),
    has_LTHO_exemp = ifelse(exe_longtime_homeowner > 0, 1, 0),
    has_DI_exemp = ifelse(exe_disabled > 0, 1, 0),
    has_VR_exemp = ifelse(exe_vet_returning > 0, 1, 0),
    has_DV_exemp = ifelse(exe_vet_dis_lt50 + exe_vet_dis_50_69 + exe_vet_dis_ge70 > 0, 1, 0),
    has_AB_exemp = ifelse(exe_abate > 0, 1, 0),
    in_tif = ifelse(tax_code_num %in% tif_distrib$tax_code_num, 1, 0)
  )



## Test Point -------------------------
## add a test and break here if there are any observations with CHECK ME
# pin_data %>% 
# 
#   mutate(
#     av = av_clerk,
#     final_tax_to_dist = ifelse(in_tif == 0, (taxable_eav-all_exemptions)*tax_code_rate, 
#                                ifelse(in_tif == 1, (taxable_eav-all_exemptions)*tax_code_rate * (1-tax_code_distribution_pct), "CHECK ME")),
#     final_tax_to_tif = ifelse(in_tif == 1, (taxable_eav-all_exemptions)*tax_code_rate * tax_code_distribution_pct, 0),
#     
#     final_tax_to_dist_adj = ifelse(in_tif == 0, (taxable_eav_adj-all_exemptions)*tax_code_rate, 
#                                ifelse(in_tif == 1, (taxable_eav-all_exemptions)*tax_code_rate* (1-tax_code_distribution_pct), "CHECK ME")),
#     final_tax_to_tif_adj = ifelse(in_tif == 1, (taxable_eav_adj-all_exemptions)*tax_code_rate * tax_code_distribution_pct, 0)) |>
#   
#   summarize(n_checkmes = sum(final_tax_to_dist == "CHECK ME"),
#             n_checkmesadj = sum(final_tax_to_dist_adj == "CHECK ME"))


# More pin variables ------------------------

pin_data <- pin_data %>%
 
  mutate(
    av = av_clerk,
    final_tax_to_dist = ifelse(in_tif == 0, (taxable_eav-all_exemptions)*tax_code_rate, 
                               ifelse(in_tif == 1, (taxable_eav-all_exemptions)*tax_code_rate * (1-tax_code_distribution_pct), 0)),
    final_tax_to_tif = ifelse(in_tif == 1, (taxable_eav-all_exemptions)*tax_code_rate * tax_code_distribution_pct, 0),
    
    final_tax_to_dist_adj = ifelse(in_tif == 0, (taxable_eav_adj-all_exemptions)*tax_code_rate, 
                               ifelse(in_tif == 1, (taxable_eav-all_exemptions)*tax_code_rate* (1-tax_code_distribution_pct), 0)),
    final_tax_to_tif_adj = ifelse(in_tif == 1, (taxable_eav_adj-all_exemptions)*tax_code_rate * tax_code_distribution_pct, 0),

    # taxing district revenue = taxable eav * tax rate so rearrange the formula:
    taxed_eav = final_tax_to_dist / tax_code_rate,
    
    total_value_eav = ((final_tax_to_dist + final_tax_to_tif)/ tax_code_rate) + all_exemptions + abatements,
    
    taxed_av =  taxed_eav / eq_factor, # current value that taxing agencies can tax for their levies
    
    ## FMV * assessment rate = AV
    taxed_fmv = taxed_av / loa,
    #taxed_fmv = ifelse(is.nan(taxed_fmv), 0, taxed_fmv),
    
    fmv = av / loa,
    fmv = ifelse(is.na(fmv), 0, fmv),
    
    ## untaxable value = exempt EAV from abatements and exemptions
    untaxable_value_eav = all_exemptions + abatements +

      ## TIF increment EAV above frozen EAV, which becomes TIF revenue
      (final_tax_to_tif /  tax_code_rate) +

      ## difference between 25% and reduced level of assessment for incentive class properties. Excludes TIF increment when calculating the difference!
     ifelse(between(class, 600, 899), (taxed_av/loa*0.25 - taxed_av)*eq_factor, 0),

    #  manually adjust untaxable value of class 239 properties
    untaxable_value_eav = ifelse(class == 239,
                                 eq_av-taxed_eav, untaxable_value_eav),

    untaxable_value_av = untaxable_value_eav / eq_factor,
    untaxable_value_fmv = untaxable_value_av / loa,
    untaxable_value_fmv = ifelse(is.nan(untaxable_value_av), 0, untaxable_value_av),
    
    exempt_eav_inTIF = ifelse(in_tif == 1,
                              all_exemptions, 0),
    
    exempt_eav = all_exemptions + abatements, # EAV exempt from taxation due to homestead exemptions and abatements
    
    exempt_fmv = exempt_eav / eq_factor / loa,  # FMV exempt from taxation due to homestead exemptions and abatements
    
    fmv_inTIF = ifelse(in_tif==1,
                       av/loa, 0),
    
    fmv_tif_increment = ifelse(final_tax_to_tif > 0,
                               ((final_tax_to_tif / tax_code_rate) / eq_factor ) / loa, 0),
    
    
    fmv_incents_inTIF = ifelse(incent_prop == 1 & in_tif == 1,
                               fmv, 0),
    fmv_incents_tif_increment = ifelse(incent_prop == 1 & final_tax_to_tif > 0 ,
                                       ((final_tax_to_tif / tax_code_rate) / eq_factor ) / loa, 0),
    eav_incents_inTIF = fmv_incents_inTIF * loa * eq_factor
  )

write_csv(pin_data, file = paste0("./Output/Dont_Upload/0_joined_PIN_data_", i, "_test.csv"))



 # Tax Rate change -------------------------------------

pin_data <- read_csv(paste0("./Output/Dont_Upload/0_joined_PIN_data_", i, "_test.csv"))

muni_ratechange <- pin_data |> 
  group_by(clean_name) |>
  
  summarize(
    classgroup_PC = n(),
    pins_withincents = sum(ifelse(class >= 600 & class < 900, 1,0)),
    fmv_incentive = sum(ifelse(class >=600 & class <900, fmv, 0), na.rm = TRUE),
    #fmv_taxed =  sum(taxed_fmv, na.rm=TRUE),
    fmv_incents_inTIFs = sum(ifelse(class >=600 & class <900 & final_tax_to_tif > 0, fmv, 0), na.rm = TRUE),
    fmv_inTIF = sum(ifelse(final_tax_to_tif > 0, fmv, 0), na.rm=TRUE),
    fmv_tif_increment = sum(fmv_tif_increment, na.rm=TRUE),
    fmv_untaxable_value = sum(untaxable_value_fmv , na.rm=TRUE),
    fmv_exemptions = sum(all_exemptions/eq_factor/loa, na.rm=TRUE),
    fmv_abatements = sum(exe_abate/eq_factor/loa, na.rm=TRUE),
    zero_bill = sum(zero_bill, na.rm=TRUE),
    fmv_residential = sum(ifelse(class %in% c(200:399), fmv, 0), na.rm = TRUE),
    fmv_C2 = sum(ifelse(class %in% c(200:299), fmv, 0), na.rm = TRUE),
    
    fmv_industrial = sum(ifelse(class %in% industrial_classes, fmv, 0), na.rm = TRUE),
    fmv_commercial = sum(ifelse(class %in% commercial_classes, fmv, 0), na.rm = TRUE),
    
    current_rate_avg = mean(tax_code_rate),
    avg_C2_bill_noexe = mean(ifelse(between(class,200,299) & all_exemptions == 0, (final_tax_to_dist + final_tax_to_tif), NA), na.rm=TRUE),
    avg_C2_bill_withexe = mean(ifelse(between(class,200,299) & all_exemptions > 0, (final_tax_to_dist + final_tax_to_tif), NA), na.rm=TRUE),
    av_taxed = sum(taxed_av, na.rm = TRUE),
    untaxable_value_av = sum(untaxable_value_av, na.rm=TRUE),
    av = sum(av),
    eav_taxed = sum(taxed_av*eq_factor), 
    eav_untaxable = sum(untaxable_value_eav, na.rm=TRUE),
    eav_tif_increment = sum(final_tax_to_tif/tax_code_rate, na.rm=TRUE),
    eav_max = sum(fmv*loa*eq_factor, na.rm=TRUE),
    fmv = sum(fmv, na.rm=TRUE),
    pins_in_class = n(),
    all_exemptions = sum(all_exemptions),   # in EAV
    abatements = sum(exe_abate),            # in EAV
    eav_incents_inTIFs = sum(ifelse(class >=600 & class <=900 & in_tif == 1, taxed_av*eq_factor, 0), na.rm = TRUE),
    final_tax_to_dist = sum(final_tax_to_dist),
    final_tax_to_tif = sum(final_tax_to_tif),
    eav = sum(eq_av),
    new_TEAV_noIncents = sum(ifelse(class >=600 & class < 900,
                                    (taxed_av*eq_factor/loa)*0.25, taxed_av*eq_factor), na.rm=TRUE),
    
    ####### Not used currently
    # new_TEAV_noC6 = sum(ifelse( class >=600 & class <700, 
    #                             (taxed_av*eq_factor/loa)*0.25 , taxed_av*eq_factor)),
    # new_TEAV_noC7 = sum(ifelse(class >=700 & class <800,
    #                            (taxed_av*eq_factor/loa)*0.25, taxed_av*eq_factor)),
    # new_TEAV_noC8 = sum(ifelse(class >=800 & class <900, (taxed_av*eq_factor/loa)*0.25, taxed_av*eq_factor)),
    # 
    #######
    
    new_TEAV_vacant_noIncents = sum(ifelse(class >=600 & class <900,
                                           0, taxed_av*eq_factor))
  ) |>
  mutate(
    
    new_TEAV_noExemps = eav_taxed + all_exemptions, # does not include abatements
    new_TEAV_noAbates = eav_taxed + abatements, # include only abatements, not other exemption types
    
    # amount of EAV from taxing an additional 15% of the AV if incentive properties didn't exist
    forgone_EAV_incent = #class_group %in% incentive_majorclasses,
      #incent_prop == "Incentive", 
      new_TEAV_noIncents - eav_taxed) |>
  #cbind(table_cook) |>
  mutate(
    # Absolute maximum TEAV: No Exemptions, no abatements, no TIFS, no Incentive properties
    # Commercial and industrial assessed at 25%
    TEAV_max = eav_taxed + all_exemptions + abatements + eav_tif_increment + forgone_EAV_incent,
    
    # no exemptions or incentive classifications:
    TEAV_neither = eav_taxed + all_exemptions + forgone_EAV_incent,
    
    rate_noExe = final_tax_to_dist / new_TEAV_noExemps * 100,
    rate_noAbate = final_tax_to_dist / new_TEAV_noAbates * 100,
    rate_noInc = final_tax_to_dist / new_TEAV_noIncents * 100,
    rate_neither = final_tax_to_dist / TEAV_neither * 100, 
    rate_noTIFs = final_tax_to_dist / (eav_taxed + eav_tif_increment) * 100,
    rate_vacant = final_tax_to_dist / new_TEAV_vacant_noIncents* 100,
    rate_lowest = final_tax_to_dist / TEAV_max * 100,
    # rate_noC6 = levy / new_TEAV_noC6 * 100,
    # rate_noC7 = levy / TEAV_noC7 * 100,
    # rate_noC8 = levy / TEAV_noC8 * 100,
    rate_current = final_tax_to_dist / eav_taxed * 100,
    change_noInc = rate_current - rate_noInc,
    change_neither = rate_current - rate_neither,
    change_noTIF = rate_current - rate_noTIFs,
    change_noExe = rate_current - rate_noExe,
    change_vacant = rate_current - rate_vacant,
    change_lowest = rate_current - rate_lowest
  )  |>
  mutate(across(contains("rate_"), round, digits = 2)) |>
  mutate(across(contains("change_"), round, digits = 2))

write_csv(muni_ratechange, paste0("./Output/muni_ratechange_", i, "_test.csv"))


# Tax Code Calculations -------------------------

taxcodes_current <- pin_data |> 
  group_by(tax_code_num) |>
  summarize(
    av = sum(av),
    #eav = sum(eav),
    equalized_AV = sum(eq_av),
    pins_in_class = n(),
    current_exemptions = sum(all_exemptions),
    HO_exemps = sum(exe_homeowner),
    tax_code_rate = first(tax_code_rate), 
    final_tax_to_dist = sum(final_tax_to_dist, na.rm = TRUE), # used as LEVY amount!! 
    final_tax_to_tif = sum(final_tax_to_tif, na.rm = TRUE),
    tax_amt_exe = sum(all_exemptions*tax_code_rate, na.rm = TRUE), 
    tax_amt_pre_exe = sum(av_clerk*eq_factor*tax_code_rate, na.rm = TRUE), 
    tax_amt_post_exe = sum((av_clerk*eq_factor-all_exemptions)*tax_code_rate, na.rm = TRUE)  ) |>
  
  mutate(total_bill_current = final_tax_to_dist + final_tax_to_tif) |>
  mutate(cur_comp_TC_rate = tax_code_rate) |>
  mutate(current_taxable_eav = final_tax_to_dist/(cur_comp_TC_rate/100),
         new_taxable_eav = final_tax_to_dist/(cur_comp_TC_rate/100) + HO_exemps) |>
  mutate(new_comp_TC_rate = (final_tax_to_dist / new_taxable_eav)*100) |>
  mutate(new_comp_TC_rate = ifelse(is.nan(new_comp_TC_rate), cur_comp_TC_rate, new_comp_TC_rate)) |>
  select(tax_code_num, cur_comp_TC_rate, new_comp_TC_rate, current_taxable_eav, new_taxable_eav, everything())

taxcode_taxrates <- taxcodes_current |> 
  select(tax_code_num, cur_comp_TC_rate, new_comp_TC_rate, current_exemptions, HO_exemps)


# Tax Burden by municipalit and major class ---------------
mc_burden <- pin_data |>
  left_join(taxcode_taxrates, by = "tax_code_num") |>
  group_by(clean_name, class_1dig) |>
  
  ## calculate taxbase from each major class 
  ## and the amount of taxes currently collected from each
  summarize(group_taxbase= sum(taxed_eav),
            group_taxes_current = sum(taxed_eav * (tax_code_rate/100)),
            hyp_group_taxbase = sum(taxed_eav + all_exemptions, na.rm = T),
            hyp_group_taxes = sum( (taxed_eav + all_exemptions) * (new_comp_TC_rate/100), na.rm = T)
     )  |>
  mutate(across(c(group_taxbase:hyp_group_taxes), round, 0)) |>
  group_by(clean_name) |>
  
  mutate(
    muni_taxbase = sum(group_taxbase, na.rm=T),
    muni_levy = sum(group_taxes_current, na.rm = T)
  ) |>
  ungroup() |>
  mutate(
         pct_eav = group_taxbase / muni_taxbase,
         pct_taxburden_current = group_taxes_current / muni_levy,
         hyp_pct_taxburden = hyp_group_taxes / muni_levy) |>
  mutate(
         burden_shift = (pct_taxburden_current - hyp_pct_taxburden)*100)

write_csv(mc_burden, paste0("./Output/muni_burden_shift_", i, "_test.csv"))
}
```




Note: The EAV from the pin table is the original EAV (AV \* equalizer) without considering TIFs or exemptions.

taxable eav is the equalized final assessed value. 

taxed eav is the amount of eav that is taxable by local taxing agencies (non-TIF districts)

