---
title: "Abatement Use (i.e., exe_abate from PIN table) Over Time"
subtitle: "The What's and Whens"
author: "MVH & AWM"
date: "June 27, 2024"
format: 
  html:
    embed-resources: true
    theme: lumen
    code-fold: true
    code-line-numbers: true
    code-overflow: wrap
    toc: true
    toc-location: left
    df-print: paged
knitr: 
  opts_chunk:
    warning: true
    message: false
---

```{r setup}

library(tidyverse)

df <- read_csv("./Output/comm_ind_PINs_2006-2022.csv") |>
  as.data.frame() %>% filter(year == 2022) %>% mutate(tax_code_num = as.character(tax_code_num))

source("scripts/helper_tc_muninames_2022.R")

tc_muninames <- tc_muninames |>
  mutate(tax_code_num = as.character(tax_code_num)) %>% select(-year)

df <- df |>
  left_join(tc_muninames, by = "tax_code_num")

```

```{r abate_by_year}
#| warning: false

df |>
  filter(exe_abate > 0) |>
  group_by(year) |>
  summarize(n = n())

abate_list <- df |>
  filter(exe_abate > 0) |>
  filter(year == 2022) |>
  arrange(desc(av_clerk)) |>
  reframe(pin, class, av_clerk, Alea_cat, tax_code_num)

abate_TC <- df  |>
  filter(exe_abate > 0) |>
  group_by(tax_code_num) |> 
  summarize(abate_PC = n())


```

# Abatement PIN Exploration

```{r top_10_av}

abate_list |>
  head(10)

```

```{r 2022_pins}

df |>
  filter(year.x == 2022) |>
  filter(exe_abate > 0) |>
  #filter(year == 2022) |>
  group_by(clean_name) |>
  summarize(n = n(), av = sum(av_clerk)) |>
  arrange(desc(n))

df |>
  filter(year.x == 2022) |>
  filter(exe_abate > 0) |>
  #filter(year == 2022) |>
  group_by(clean_name) |>
  summarize(n = n(), av = sum(av_clerk)) |>
  arrange(desc(av))

```

I guess it is also Alsip?

```{r alsip}

df |>
  filter(year.x == 2022) |>
  #filter(clean_name == "Alsip") |>
  filter(exe_abate > 0) |>
  select(clean_name, pin, class, tax_code_num, av_clerk, exe_abate, class_desc, Alea_cat,
         incent_prop) |>
  arrange(desc(exe_abate))
  

```

Observations:

There are a lot of Industrial Buildings and Gas Stations.

NONE have incentive classifications.

Let's look at a few!

### Highest AV (and abatement value!) in Alsip 2022

PIN: 24264070100000
Class: 523
Type: Gasoline Station
AV_Clerk: $301,611
exe_abate: $1,476,960
Address: 12680 S KEDZIE AVE

[image]

### Second highest AV...across the street in Alsip 2022!

[image]


```{r bedford_2022}

df |>
  filter(year.x == 2022) |>
  filter(clean_name == "Bedford Park") |>
  filter(exe_abate > 0) |>
  select(pin, class, tax_code_num, av_clerk, exe_abate, class_desc, Alea_cat,
         incent_prop)

```

```{r alsip_over_time}

df <- df |>
  filter(year.x == )

```



