---
title: "Frequently Asked Questions"
format: html
---

In this section, we address several recurring questions we received from stakeholders throughout drafting the reports. These questions focus on our data sources and subsequent analysis. We encourage readers with general questions about Cook County's property tax system to review the material published by the Assessor, Treasurer, Recorder, and President's Offices.

*Did you account for the COVID factor?*

After we accounted for the general slowdown in economic growth associated with the COVID-19 pandemic, we identified no patterns in the data reflecting application of a policy intervention through Cook County's property tax system in the form of a "COVID factor." To the extent any such policies exist, they align with general time-trends in property value and use.

While COVID is associated with waiver of certain fair-pay and compliance requirements for incentive eligibility (as discussed in the incentives study), even waiver of that requirement is similarly not reflected in our data.

*Are there any known weaknesses in your data?*

While we faced several data limitations, these limitations were addressed in the relevant sections of the reports.

*Why don't your numbers match the Treasurer/Clerk/Assessor's numbers for year 20XX?*

Overall, our numbers closely mirror those of the Cook County agencies responsible for maintaining property tax records. This outcome is likely a result of use of a common data set. While rounding errors do exist, our record of tax bills--used to generate our report data--are consistently validated by the Cook County Assessor's Office.
