---
title: "Incentive Survival Over Time"
author: "MVH"
format: 
  html:
    df-print: paged
    code-fold: true
    code-download: true
    toc: true
---

```{r setup, warning = FALSE, output = FALSE}

library(tidyverse)

knitr::opts_chunk$set(warning = FALSE, message = FALSE)

options(scipen = 999)

```

```{r}

incPINs <- read_csv("./Output/incentivePINs_allyears.csv")

```

```{r}

incPINs2011 <- incPINs %>%
  filter(year == 2011) %>%
  filter(between(class, 600, 899)) %>%
  mutate(pinYear = 2011) %>%
  select(pin, pinYear, year, class, av_clerk)

```

```{r}
#| label: tbl-IncentProps2021
#| code-fold: true
#| column: screen
#| tbl-cap: "2011 Incentive Properties by Class"

incPINs2011 %>%
  group_by(class) %>%
  mutate(n = n()) %>%
  summarize(n) %>%
  arrange(desc(n)) %>%
  distinct() %>%
ggplot(aes(n)) +
  geom_bar()

```


```{r}
#| code-fold: true
#| column: screen
#| tbl-cap: "2021 Incentive Properties (Combined)"

incPINs2011 %>%
  summarize(
    n = n(), av= sum(av_clerk),
    .by = c("class")
  ) %>%
  arrange(-n)
```

```{r}

incPINs2021 <- incPINs %>%
  filter(year == 2021) %>%
  filter(between(class, 600, 899)) %>%
  mutate(pinYear = 2021) %>%
  select(pin, year, class, av_clerk)

inc2021List <- as.list(incPINs2021$pin)

```

```{r}
#| label: tbl-IncentProps2021
#| code-fold: true
#| column: screen
#| tbl-cap: "2021 Incentive Properties by Class"

incPINs2021 %>%
  summarize(
    n = n(), sumAV = sum(av_clerk),
    .by = c("class")
  ) %>%
  distinct() %>%
  arrange(-n)

```

```{r}

incPINsSurvive21from11 <- left_join(incPINs2021, incPINs2011, by = "pin", keep = FALSE)

```

```{r}

incPINsSurvive21from11 <- incPINsSurvive21from11 %>%
 filter(!is.na(av_clerk.y)) %>%
  rename(class2011 = class.x,
         class2021 = class.y)

incPINsSurvive21from11 %>%
  mutate(classChange = as.numeric(if_else(class2021 != class2021, "1", "0"))) %>%
  group_by(class2011) %>%
  summarize(n = n(), Changed_Class = sum(classChange), sumAV2011 = sum(av_clerk.x), sumAV2021 = sum(av_clerk.y)) %>%
  distinct() %>%
  arrange(-n)

incPINsSurvive21from11 %>%
  mutate(classChange = as.numeric(if_else(class2011 != class2021, "1", "0"))) %>%
  group_by(class2021) %>%
  summarize(n = n(), Changed_Class = sum(classChange), sumAV2011 = sum(av_clerk.x), sumAV2021 = sum(av_clerk.y)) %>%
  distinct() %>%
  arrange(-n)
```

```{r}
#| code-fold: true
#| column: screen
#| tbl-cap: "2021 Incentive Properties That Changed Class since 2011"

incPINsSurvive21from11 %>%
  mutate(classChange = as.numeric(if_else(class2011 != class2021, "1", "0"))) %>%
  group_by(class = class2021) %>%
  summarize(n = n(), Changed_Class = sum(classChange), sumAV2011 = sum(av_clerk.x), sumAV2021 = sum(av_clerk.y)) %>%
  distinct() %>%
  arrange(-n)

```

```{r}


```

Ignoring class

```{r, eval = F}

ptax_pins <- read_csv("./Output/incentivePINs_allyears.csv") # file created in helper_pull_incentivepins_allyears.R


ptax_pins %>% group_by(pin) %>% summarize(count = n()) %>% arrange(-count)
# 5858 incentive PINs have existed at some point in time.
ptax_pins %>% group_by(year) %>% summarize(incentive_count = n())
# 4383 existed in 2022. 
# 3652 existed in 2021, etc.

ptax_pins %>% group_by(pin) %>% summarize(count = n()) %>% filter(count > 16)
# 632 PINs have existed AND been incentive properties for all years in database.

ptax_pins %>% mutate(parcel = str_sub(pin, 1, 10) ) %>%
  group_by(parcel) %>% summarize(count = n())

ptax_pins %>% mutate(block = str_sub(pin, 1, 7) ) %>%
  group_by(block) %>% summarize(count = n())

ptax_pivot_changed <- ptax_pins %>% 
  pivot_wider(id_cols = c(pin), names_from = "year", values_from =  "class") %>%
  mutate(change = ifelse(as.numeric(`2021`)-as.numeric(`2006`) != 0,
                         1, 0))%>% 
  filter(change !=0)

ptax_pivot_changed
```

```{r}

incPINs %>% 
  group_by(year) %>% 
  filter(between(class, 600, 900)) %>%
  summarize(incentive_count = n()) %>%
  ggplot(aes(x = year, y = incentive_count)) +
  geom_col() +
  labs(
    title = "Incentive PINs by Year"
  ) +
  theme_classic()
```

```{r}
#| code-fold: true
#| column: screen
#| tbl-cap: "2021 Incentive Properties That Changed Class since 2011"

ptax_pivot_changed %>%
  rename(class = '2021') %>%
  filter(!is.na(class)) %>%
  summarize(n = n(),
            .by = class) %>%
  arrange(-n)
```
