---
title: "Burden Shift from Incentive Properties" 
format: 
  html:
    df-print: paged
    code-fold: true
    code-download: true
    toc: true
    toc-location: left
    fig-cap-location: top
    fig-height: 10

---

**Preliminary Setup**

```{r setup, warning = FALSE, output = FALSE}

library(tidyverse)
library(ptaxsim)
library(DBI)
library(httr)
library(jsonlite)
library(glue)
library(sf)

knitr::opts_chunk$set(warning = FALSE, message = FALSE)


```

```{r}
#| code-fold: true

nicknames <- readxl::read_excel("./Necessary_Files/muni_shortnames.xlsx")


MuniLevel <- read_csv("./Output/ptaxsim_muni_level_2006-2021.csv") %>%
  filter(year == 2021) %>%
  left_join(nicknames) %>% 
  select(clean_name, cur_comp_muni_rate) %>%
  rename(cur_munilevel_rate = cur_comp_muni_rate)


MC_sums <- read_csv("./Output/ptaxsim_muni_MC_2006-2021.csv") %>% 
  filter(year == 2021) %>% 
  left_join(nicknames) 

eqfact21 <- 3.0027 #2021 CC Equalization Factor
```

```{r}
incentive_sums <- MC_sums %>%
  left_join(MuniLevel) %>%
  mutate(
         incentive = ifelse(major_class_code %in% c("6A","6B", "6C", "7A","7B","7C","8"), "Incentive", "Non-Incentive"),
         incent_type = ifelse(major_class_code %in% c("6A","6B", "6C"), "Industrial", ifelse(major_class_code %in% c("7A","7B","7C", "8"), "Commercial", "Not Incentive Prop"))) %>%
  group_by(year, clean_name, incentive, cur_munilevel_rate) %>%
  summarize(av = sum(av),
            eav = sum(eav),
            pins_in_muni = sum(pins_in_muni), # all pins
            incent_pins = n(),
            final_tax_to_dist = sum(final_tax_to_dist),
            current_taxable_eav = sum(current_taxable_eav))%>%
  mutate(new_av = ifelse(incentive == "Incentive", av*2.5, av),
    new_taxable_eav = ifelse(incentive ==  "Incentive", current_taxable_eav * 2.5 , current_taxable_eav))

incentive_sums 

incentive_sums %>% 
  filter(incentive == "Incentive") %>% arrange(-incent_pins)


```


```{r commer_indust_incents}

incentive_pins2 <- MC_sums %>%
  mutate(
         incentive = ifelse(major_class_code %in% c("6A","6B", "6C", "7A","7B","7C","8"), "Incentive", "Non-Incentive"),
         incent_type = ifelse(major_class_code %in% c("6A","6B", "6C"), "Industrial", ifelse(major_class_code %in% c("7A","7B","7C", "8"), "Commercial", "Not Incentive Prop"))) %>%
  group_by(year, clean_name, incent_type) %>%
  summarize(av = sum(av),
            eav = sum(eav),
            pins_in_muni = n(),
            final_tax_to_dist = sum(final_tax_to_dist),
            current_taxable_eav = sum(current_taxable_eav)) %>%
  mutate(new_av = ifelse(incent_type != "Not Incentive Prop", av*2.5, av),
    new_taxable_eav = ifelse(incent_type !=  "Not Incentive Prop", current_taxable_eav * 2.5 , current_taxable_eav))

incentive_pins2

```


```{r AleaCatsToGroup}

# PTAXSIM incentive properties --------------------------------------------
# Pulled from PTAXSIM - Al PINs from 2021, filtered by class_code between 600&900
# 3652 PINs in 2021
incentive_pins <- read_csv("./Output/7_output_incentive_classes.csv") %>%
    mutate(
      # pin = as.character(pin), 
      # pin = str_pad(pin, 13, "left"),
         parcel = str_sub(pin, 1, 10),
         block = str_sub(pin, 1, 7)) 



incentive_Aleacats <- incentive_pins %>%
  left_join(nicknames)%>%
  mutate(
         incentive = ifelse(major_class_code %in% c("6A","6B", "6C", "7A","7B","7C","8"), "Incentive", "Non-Incentive"),
         incent_type = ifelse(major_class_code %in% c("6A","6B", "6C"), "Industrial", ifelse(major_class_code %in% c("7A","7B","7C", "8"), "Commercial", "Not Incentive Prop"))) %>%
  group_by(clean_name, Alea_cat) %>%
  summarize(av = sum(av),
            eav = sum(eav),
            pins_in_muni = n()) %>%
  left_join(MuniLevel) %>%
  mutate(
           # final_tax_to_dist = sum(final_tax_to_dist),
           current_rev_collected = round(cur_munilevel_rate * eav ),
           # current_taxable_eav = sum(current_taxable_eav)
          )

incentive_Aleacats
```


```{r commer_indust_incents}
incentive_sums2 <- MC_sums %>%
  left_join(MuniLevel) %>%
  mutate(
         incentive = ifelse(major_class_code %in% c("6A","6B", "6C", "7A","7B","7C","8"), "Incentive", "Non-Incentive"),
         incent_type = ifelse(major_class_code %in% c("6A","6B", "6C"), "Industrial", ifelse(major_class_code %in% c("7A","7B","7C", "8"), "Commercial", "Not Incentive Prop"))) %>%
  group_by(clean_name, incent_type, cur_munilevel_rate) %>%
  summarize(av = sum(av),
            eav = sum(eav),
            pins_in_muni = sum(pins_in_muni),
            final_tax_to_dist = sum(final_tax_to_dist),
           # current_rate = mean(cur_comp_muni_rate),
            current_taxable_eav = sum(current_taxable_eav))%>%
  mutate(new_av = ifelse(incent_type != "Not Incentive Prop", av*2.5, av),
    new_taxable_eav = ifelse(incent_type !=  "Not Incentive Prop", current_taxable_eav * 2.5 , current_taxable_eav))

incentive_sums2 <- incentive_sums2 %>% 
  group_by(clean_name) %>% 
  mutate(munilevy = sum(final_tax_to_dist),
         cur_muni_taxable_eav = sum(current_taxable_eav),
         new_muni_taxable_eav = sum(new_taxable_eav)) %>%
  ungroup() %>%
  mutate(new_comp_rate = munilevy / new_muni_taxable_eav * 100)


burden2 <- incentive_sums2 %>% 
  mutate(group_taxes_hyp = new_taxable_eav * (new_comp_rate),
         group_taxes_cur = current_taxable_eav * cur_munilevel_rate,
         pct_eav = eav / cur_muni_taxable_eav) %>%
  mutate(
    pct_taxburden_current = group_taxes_cur / munilevy,
    pct_taxburden_no_incent = group_taxes_hyp / munilevy,
    burden_shift = round(pct_taxburden_current - pct_taxburden_no_incent, digits = 2 ),
    av_change_perPIN = ifelse(incent_type %in% c("Commercial", "Industrial"), (new_av - av)/pins_in_muni, NA))

burden2 %>% arrange(clean_name) %>% select(clean_name, incent_type, burden_shift)

```


```{r}
incentive_sums <- incentive_sums %>% 
  group_by(clean_name) %>% 
  mutate(munilevy = sum(final_tax_to_dist),
         cur_muni_taxable_eav = sum(current_taxable_eav),
         new_muni_taxable_eav = sum(new_taxable_eav)) %>%
  ungroup() %>%
  mutate(new_comp_rate = munilevy / new_muni_taxable_eav * 100)




burden <- incentive_sums %>% 
  mutate(group_taxes_hyp = new_taxable_eav * (new_comp_rate),
         group_taxes_cur = current_taxable_eav * cur_munilevel_rate,
         pct_eav = eav / cur_muni_taxable_eav) %>%
    mutate(rate_change = cur_munilevel_rate - new_comp_rate) %>%

  mutate(
    pct_taxburden_current = group_taxes_cur / munilevy,
    pct_taxburden_no_incent = group_taxes_hyp / munilevy,
    
    burden_shift = round(pct_taxburden_current - pct_taxburden_no_incent, digits = 2 ),
    av_change_perPIN = ifelse(incentive == "Incentive", (new_av - av)/pins_in_muni, NA))
```


```{r}
#| code-fold: true
#| column: screen
#| tbl-cap: "Incentive Properties (Combined) Tax Rates and Burden"

burden %>% 
  filter(incentive == "Incentive" & clean_name != "NA") %>%
  select(Municipality = clean_name, cur_munilevel_rate, new_comp_rate, pct_taxburden_current, pct_taxburden_no_incent) %>% 
  mutate_if(is.numeric, ~round(., 1))

```

## Change in Composite Tax Rate 
```{r}

# as a dot graph ## 
# create order of dots
order <- burden %>%  
  as_tibble() %>% 
  filter(incentive == "Incentive") %>% 
  arrange( rate_change) %>%
  select(clean_name, cur_munilevel_rate, new_comp_rate)

# make dot graph
burden %>% 
  filter(incentive == "Incentive" & clean_name != "NA") %>%
  select(clean_name, cur_munilevel_rate, new_comp_rate, rate_change) %>% 
  pivot_longer(c("cur_munilevel_rate", "new_comp_rate"), 
               names_to = "type", values_to = "tax_rate") %>% 
  left_join(order) %>%
  ggplot(aes(x = tax_rate, y= reorder(clean_name, rate_change)))+
  geom_line(aes(group = clean_name))+ 
  geom_point(aes(color=type), size=3 )+
  theme_minimal() + 
  theme( 
    legend.title = element_blank(),
    plot.title.position = "plot",
    plot.background = element_rect(fill='transparent', color=NA) #transparent plot bg
  )+
  scale_color_brewer(palette="Paired", labels = c("Incentives", "No Incentives"), direction = 1)+
  
  labs(title = "Difference in Composite Tax Rate if Assessed at 25%",
       subtitle = "Ordered by Comp. Rate Change", x = "Composite Tax Rate (%)", y = "")
```
```{r}

# as a dot graph ## 
# create order of dots
order <- burden %>%  
  as_tibble() %>% 
  filter(incentive == "Incentive") %>% 
  arrange(cur_munilevel_rate) %>%
  select(clean_name, cur_munilevel_rate)

# make dot graph
burden %>% 
  filter(incentive == "Incentive" & clean_name != "NA") %>%
  select(clean_name, cur_munilevel_rate, new_comp_rate) %>% 
  pivot_longer(c("cur_munilevel_rate", "new_comp_rate"), 
               names_to = "type", values_to = "tax_rate") %>% 
  left_join(order) %>%
  ggplot(aes(x = tax_rate, y= reorder(clean_name, cur_munilevel_rate)))+
  geom_line(aes(group = clean_name))+ 
  geom_point(aes(color=type), size=3 )+
  theme_minimal() + 
  theme( 
    legend.title = element_blank(),
    plot.title.position = "plot",
    plot.background = element_rect(fill='transparent', color=NA) #transparent plot bg
  )+
  scale_color_brewer(palette="Paired", labels = c("Incentives", "No Incentives"), direction = 1)+
  
  labs(title = "Difference in Composite Tax Rate if Assessed at 25%",
       subtitle = "Ordered by Current Composite Tax Rate", x = "Composite Tax Rate (%)", y = "")
```


## Change in Tax Burden

```{r}

# as a dot graph ## 

order <- burden %>%  
  as_tibble() %>% 
  filter(incentive == "Incentive") %>% 
  arrange(pct_taxburden_current) %>%
  select(clean_name, pct_taxburden_current)

burden %>% 
  filter(incentive == "Incentive" & clean_name !="NA") %>%
  select(clean_name, pct_taxburden_current, pct_taxburden_no_incent) %>% 
  pivot_longer(c("pct_taxburden_current", "pct_taxburden_no_incent"), 
               names_to = "type", values_to = "tax_rate") %>% 
  left_join(order) %>%
  ggplot(aes(x = tax_rate, y= reorder(clean_name, pct_taxburden_current)))+
  
  geom_line(aes(group = clean_name))+ 
  geom_point(aes(color=type), size=3 )+
  theme_minimal() + 
  theme( 
    legend.title = element_blank(),
    plot.title.position = "plot",
    plot.background = element_rect(fill='transparent', color=NA) #transparent plot bg
  )+
  scale_color_brewer(palette="Paired", labels = c("Incentives", "No Incentives"), direction = 1)+
  
  labs(title = "Tax Burden for Incentive Properties if Assessed at 25%",
       subtitle = "Ordered by Current Tax Burden", x = "% of Levy Paid", y = "" , 
       caption = "")
```


```{r}

# as a dot graph ## 

order <- burden2 %>%  
  as_tibble() %>% 
  filter(incent_type == "Industrial") %>% 
  arrange(pct_taxburden_current) %>%
  select(clean_name, pct_taxburden_current)

burden2 %>% 
  filter(incent_type == "Industrial" & clean_name !="NA") %>%
  select(clean_name, pct_taxburden_current, pct_taxburden_no_incent) %>% 
  pivot_longer(c("pct_taxburden_current", "pct_taxburden_no_incent"), 
               names_to = "type", values_to = "tax_rate") %>% 
  left_join(order) %>%
  ggplot(aes(x = tax_rate, y= reorder(clean_name, pct_taxburden_current)))+
  
  geom_line(aes(group = clean_name))+ 
  geom_point(aes(color=type), size=3 )+
  theme_minimal() + 
  theme( 
    legend.title = element_blank(),
    plot.title.position = "plot",
    plot.background = element_rect(fill='transparent', color=NA) #transparent plot bg
  )+
  scale_color_brewer(palette="Paired", labels = c("Incentives", "No Incentives"), direction = 1)+
  
  labs(title = "Tax Burden for Industrial Properties if Assessed at 25%",
       subtitle = "Ordered by Current Tax Burden", x = "% of Levy Paid", y = "" , 
       caption = "")
```
