---
title: "Change in Median tax bill if no exemptions"
author: "Alea Wilbur"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
    df_print: paged
    code_folding: hide
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)


library(tidyverse)
library(DBI)
library(data.table)
library(ggspatial)
library(gstat)
library(here)
library(httr)
library(jsonlite)
library(ptaxsim)
library(sf)
library(stars)
library(glue)

# Create the DB connection with the default name expected by PTAXSIM functions
ptaxsim_db_conn <- DBI::dbConnect(RSQLite::SQLite(), "./ptaxsim.db/ptaxsim-2021.0.4.db")

# has all potential property classes for pins
# downloaded from CCAO gitlab website
## I used this to merge additional information to the pins and class data later on.
class_dict <- read_csv("class_dict.csv")

options(digits=4, scipen = 999)

```


```{r eval = FALSE, include = FALSE}
munis <- c("VILLAGE OF PARK FOREST", "VILLAGE OF PHOENIX","VILLAGE OF DOLTON",
           "VILLAGE OF HAZELCREST", "VILLAGE OF MIDLOTHIAN", "VILLAGE OF BEDFORD PARK",
           "VILLAGE OF BRIDGEVIEW", "VILLAGE OF RIVER GROVE", "VILLAGE OF MC COOK",
           "VILLAGE OF OAK PARK", "VILLAGE OF HOFFMAN ESTATES", "VILLAGE OF ROSEMONT",
           "VILLAGE OF HODGKINS", "VILLAGE OF WINNETKA")

munis$muni_name <- c("VILLAGE OF PARK FOREST", "VILLAGE OF PHOENIX","VILLAGE OF DOLTON",
           "VILLAGE OF HAZELCREST", "VILLAGE OF MIDLOTHIAN", "VILLAGE OF BEDFORD PARK",
           "VILLAGE OF BRIDGEVIEW", "VILLAGE OF RIVER GROVE", "VILLAGE OF MC COOK",
           "VILLAGE OF OAK PARK", "VILLAGE OF HOFFMAN ESTATES", "VILLAGE OF ROSEMONT",
           "VILLAGE OF HODGKINS", "VILLAGE OF WINNETKA")
```

```{r agency-dt, eval = FALSE}
# has EAV values, extensions by agency_num
agency_dt <- DBI::dbGetQuery(
  ptaxsim_db_conn,
  "SELECT *
  FROM agency
  WHERE year = 2021
  "
)

# grabs all unique muni names. Would be needed if creating a loop for calculating all munis
# municipality names and their agency number
# muni_agency_names <- DBI::dbGetQuery(
#   ptaxsim_db_conn,
#   glue_sql("
#   SELECT DISTINCT agency_num, agency_name, minor_type
#   FROM agency_info
#   WHERE agency_name IN ({munis$muni_name*})
#   ",
#   .con = ptaxsim_db_conn
#   )
# )

muni_agency_names <- DBI::dbGetQuery(
  ptaxsim_db_conn,
  "SELECT DISTINCT agency_num, agency_name, minor_type
  FROM agency_info
  WHERE minor_type = 'MUNI'
  OR agency_num = '020060000'  

  "
)

muni_agency_names <- muni_agency_names %>% 
    mutate(first6 = str_sub(agency_num,1,6),
         first5 = str_sub(agency_num,1,5)) %>% 
  select(-minor_type)



muni_tax_codes <- DBI::dbGetQuery(
  ptaxsim_db_conn,
  glue_sql("
  SELECT*
  FROM tax_code
  WHERE agency_num IN ({muni_agency_names$agency_num*})
  AND year = 2021
  ",
  .con = ptaxsim_db_conn
  )
)# %>% select(-agency_rate)


nicknames <- readxl::read_excel("muni_shortnames.xlsx")

#Makes a list of ALL taxing agencies, including TIFs, SSAs, etc.

# all agency names, numbers, and types
# includes TIF and non-TIF agencies
all_taxing_agencies <- DBI::dbGetQuery(
  ptaxsim_db_conn,
  "SELECT agency_num, agency_name, major_type, minor_type
  FROM agency_info
  "
  ) %>%
  mutate(first6 = str_sub(agency_num,1,6),
         first5 = str_sub(agency_num,1,5))

all_taxing_agencies <- all_taxing_agencies %>% 
  left_join(muni_agency_names, by = c("first5", "first6")) %>% 
  rename(muni_name =  agency_name.y,
        muni_num = agency_num.y,
        agency_name = agency_name.x,
        agency_num = agency_num.x)


```

## Current Values

```{r eval = FALSE}
muni_pins <- DBI::dbGetQuery(
  ptaxsim_db_conn,
  glue_sql(
  "SELECT DISTINCT pin, class, tax_code_num
  FROM pin
  WHERE tax_code_num IN ({muni_tax_codes$tax_code_num*})
  AND year = 2021
  ",
  .con = ptaxsim_db_conn
))

#all_muni_pins <-read_csv("all_muni_pins.csv")

# Normal output from lookup_pin() command. Includes all types of exemptions
exe_dt <- lookup_pin(2021, muni_pins$pin) %>%
  setDT(key = c("year", "pin"))




taxbills_current <- tax_bill(2021, 
                  muni_pins$pin, 
                  pin_dt = exe_dt, # default option
                  simplify = FALSE)

class_dict$class_code <- as.character(class_dict$class_code)

pin_bills_current <- taxbills_current %>%
  left_join(class_dict, by = c("class" = "class_code")) %>% # add major property types to pin data
  group_by(major_class_code, major_class_type, tax_code, pin) %>%
  mutate(total_bill = final_tax_to_dist+final_tax_to_tif) %>%
  arrange(av) %>%
  summarize(total_billed = sum(total_bill, na.rm = TRUE),
   # median_bill = median(total_bill, na.rm=TRUE),
   av = first(av),
   eav = first(eav),
            final_tax_to_dist = sum(final_tax_to_dist, na.rm = TRUE),
            final_tax_to_tif = sum(final_tax_to_tif, na.rm = TRUE),
            tax_amt_exe = sum(tax_amt_exe, na.rm = TRUE), # revenue lost due to exemptions
            tax_amt_pre_exe = sum(tax_amt_pre_exe, na.rm = TRUE), # total rev before all exemptions
            tax_amt_post_exe = sum(tax_amt_post_exe, na.rm = TRUE), # total rev after all exemptions
        rpm_tif_to_cps = sum(rpm_tif_to_cps), # not used
        rpm_tif_to_rpm = sum(rpm_tif_to_rpm), # not used
         rpm_tif_to_dist = sum(rpm_tif_to_dist), # not used
          tif_share = mean(tif_share), # not used
       ) %>%
  mutate(stage = "With exemptions")



pin_bills_current <- pin_bills_current %>%  
  full_join(muni_tax_codes, 
                      by = c("tax_code" = "tax_code_num")) %>%
  left_join(muni_agency_names) %>%
  left_join(nicknames) %>%

  mutate(bill_total = final_tax_to_tif+final_tax_to_dist,
Type = "With exemptions") #%>% select(agency_name, Type, tax_amt_exe, bill_total)


head(pin_bills_current)
#write.csv(pin_bills_current, "pin level total bills.csv")


```


## Simulation: No Exemptions 

```{r eval = FALSE}
# Changes all exemptions to 0 for all pins. 
# This table will then go INSIDE of the taxbill() comand
# for no exemptions simulation
no_exe_dt <- lookup_pin(2021, muni_pins$pin)# %>%
 # mutate(across(starts_with("exe_"), ~0)) %>%
 # setDT(key = c("year", "pin"))


no_exe_dt[, tax_code := lookup_tax_code(year, pin)]

exe_cols <- names(no_exe_dt)[startsWith(names(no_exe_dt), "exe_")]
taxcode_sum_no_exe <- no_exe_dt[,
  .(exe_total = sum(rowSums(.SD))),
  .SDcols = exe_cols,
  by = .(year, tax_code)
]

# recalculate the base
# change agency data table and their tax rate

t_agency_dt_no_exe <- lookup_agency(2021, no_exe_dt$tax_code)
t_agency_dt_no_exe[
  taxcode_sum_no_exe,
  on = .(year, tax_code),
  agency_total_eav := agency_total_eav + exe_total
]

no_exe_dt[, (exe_cols) := 0][, c("tax_code") := NULL]


taxbills_no_exemps <- tax_bill(2021, 
                  pin_vec = muni_pins$pin,
                  agency_dt = t_agency_dt_no_exe,
                  pin_dt = no_exe_dt,
                  simplify = FALSE
)[
  , stage := "No exemptions" # makes a new variable for when we join current and hypotheticals together in a graph and table
]

head(taxbills_no_exemps)

class_dict$class_code <- as.character(class_dict$class_code)

pin_bills_no_exemps <- taxbills_no_exemps %>%
  left_join(class_dict, by = c("class" = "class_code")) %>% # add major property types to pin data
  group_by(major_class_code, major_class_type, tax_code, pin) %>%
  mutate(total_bill = final_tax_to_dist+final_tax_to_tif) %>%
  arrange(av) %>%
  summarize(total_billed = sum(total_bill, na.rm = TRUE),
            av = first(av),
    eav = first(eav),
            final_tax_to_dist = sum(final_tax_to_dist, na.rm = TRUE),
            final_tax_to_tif = sum(final_tax_to_tif, na.rm = TRUE),
            tax_amt_exe = sum(tax_amt_exe, na.rm = TRUE), # revenue lost due to exemptions
            tax_amt_pre_exe = sum(tax_amt_pre_exe, na.rm = TRUE), # total rev before all exemptions
            tax_amt_post_exe = sum(tax_amt_post_exe, na.rm = TRUE), # total rev after all exemptions
        rpm_tif_to_cps = sum(rpm_tif_to_cps), # not used
        rpm_tif_to_rpm = sum(rpm_tif_to_rpm), # not used
         rpm_tif_to_dist = sum(rpm_tif_to_dist), # not used
          tif_share = mean(tif_share), # not used
       ) %>%
  mutate(stage = "Without exemptions")

pin_bills_no_exemps <- pin_bills_no_exemps %>% 
   #   mutate(tax_code_num = as.character(tax_code_num)) %>%
    left_join(muni_tax_codes, by = c("tax_code" = "tax_code_num"))%>%
  left_join(muni_agency_names) %>%
  left_join(nicknames) %>%
  mutate(bill_total = final_tax_to_tif+final_tax_to_dist,
Type = "Without Exemptions") #%>% 

#write_csv(pin_bills_no_exemps, "pin level total bills-exemptions removed.csv")
```


```{r}

pin_bills_no_exemps <- read_csv("pin level total bills-exemptions removed.csv")

pin_bills_current <- read_csv("pin level total bills.csv")

bills_current <- pin_bills_current %>% 
  group_by(clean_name) %>% 
  arrange(av) %>%
  summarize(total_billed = sum(bill_total, na.rm=TRUE),
            median_bill = median(bill_total, na.rm=TRUE),
            median_AV = median(av, na.rm= TRUE),
            eav = median(eav, na.rm=TRUE),
          #  class = median(class),
            type = "Current Exemptions")

bills_current

bills_noexemps <- pin_bills_no_exemps %>% 
  group_by(clean_name) %>% 
  arrange(av) %>%
  summarize(
    total_billed = sum(bill_total, na.rm=TRUE),
            median_bill = median(bill_total, na.rm=TRUE),
    median_AV = median(av, na.rm=TRUE),
            eav = median(eav, na.rm=TRUE),
            type = "Without Exemptions")

bills_noexemps
```

# Median bill (all property types)

```{r}


bills_difference <- rbind(bills_current, bills_noexemps)  %>% arrange(clean_name) 

bills_difference

difference_table_allpropertytypescombined <- bills_difference %>% 
  pivot_wider(id_cols = clean_name, names_from = type, values_from = median_bill) %>%
  mutate(Median_bill_difference = `Without Exemptions`-`Current Exemptions` )
difference_table_allpropertytypescombined

write_csv(difference_table_allpropertytypescombined, "median_bill_allClassesCombined.csv")

```

# Median Bill (Class 2 Properties)

```{r}
bills_byClass_current <- pin_bills_current %>% group_by(clean_name, major_class_code) %>%
  arrange(av) %>%
  summarize(total_billed = sum(bill_total, na.rm=TRUE),
            median_bill = median(bill_total, na.rm=TRUE),
            av = median(av, na.rm=TRUE),
            eav = median(eav, na.rm=TRUE),
            type = "Current Exemptions")
bills_byClass_current

bills_byClass_noexemps <- pin_bills_no_exemps %>% group_by(clean_name, major_class_code) %>%
  arrange(av) %>%
  summarize(total_billed = sum(bill_total, na.rm=TRUE),
            median_bill = median(bill_total, na.rm=TRUE),
                        av = median(av, na.rm=TRUE),
            eav = median(eav, na.rm=TRUE),
            type = "Without Exemptions")
bills_byClass_noexemps


bills_difference_byClass <- rbind(bills_byClass_current, bills_byClass_noexemps) %>% 
  ungroup() %>% 
  arrange(clean_name, major_class_code) 

bills_difference_byClass

bills_difference_byClass <- bills_difference_byClass %>% 
  pivot_wider(id_cols = c(clean_name, major_class_code, av, eav), names_from = type, values_from = median_bill) %>%
  mutate(Median_bill_difference = `Without Exemptions` - `Current Exemptions` ) %>%
  select(clean_name, major_class_code, Median_bill_difference, everything())

class_difference_table <- bills_difference_byClass %>% filter(major_class_code == 2) %>% select(clean_name, Median_bill_difference, `Current Exemptions`, `Without Exemptions`, major_class_code, everything())

class_difference_table

write_csv(bills_difference_byClass, "median_bill_byPropertyClass.csv")
write_csv(class_difference_table, "residential_billchange.csv")
```

```{r}
rm(exe_dt)
rm(muni_pins)
rm(taxbills_current)
rm(taxbills_no_exemps)


```


