---
title: "Quartiles and Deciles of AV by Municipality"
author: "Alea Wilbur"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    df_print: paged
    code_folding: hide
    code_download: true
---



```{r setup, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)


library(DBI)
library(data.table)
library(ggspatial)
library(gstat)
library(here)
library(httr)
library(jsonlite)
library(ptaxsim)
library(sf)
library(stars)
library(glue)
library(tidyverse)


# Create the DB connection with the default name expected by PTAXSIM functions
ptaxsim_db_conn <- DBI::dbConnect(RSQLite::SQLite(), "./ptaxsim.db/ptaxsim-2021.0.4.db")


options(digits=4, scipen = 999)

library(sf)
library(jsonlite)
library(httr)

# link to the API output as a JSON file
muni_shp <- read_sf("https://gis.cookcountyil.gov/traditional/rest/services/politicalBoundary/MapServer/2/query?outFields=*&where=1%3D1&f=geojson")

#muni_shp <- read_json("muni_shp.json")
nicknames <- readxl::read_excel("./Necessary_Files/muni_shortnames.xlsx")

class_dict <- read_csv("./Necessary_Files/class_dict_expanded.csv") %>% 
  mutate(class_code = as.character(class_code)) # change variable type to character so the join works.

```



```{r agency-dt}
agency_dt <- DBI::dbGetQuery(
  ptaxsim_db_conn,
  "SELECT *
  FROM agency
  WHERE year = 2021
  "
)


cook_agency_names <- DBI::dbGetQuery(
  ptaxsim_db_conn,
  "SELECT DISTINCT agency_num, agency_name
  FROM agency_info
  "
)

 


# has all tax codes and the taxing agency that taxes them. Tax code rates and agency rates. 
cook_tax_codes <- DBI::dbGetQuery(
  ptaxsim_db_conn,
  glue_sql("
  SELECT*
  FROM tax_code
  WHERE agency_num IN ({cook_agency_names$agency_num*})
  AND year = 2021
  ",
  .con = ptaxsim_db_conn
  )
)

muni_agency_names <- DBI::dbGetQuery(
  ptaxsim_db_conn,
  "SELECT DISTINCT agency_num, agency_name, minor_type
  FROM agency_info
  WHERE minor_type = 'MUNI'
  OR agency_num = '020060000'  

  "
)

muni_tax_codes <- DBI::dbGetQuery(
  ptaxsim_db_conn,
  glue_sql("
  SELECT*
  FROM tax_code
  WHERE agency_num IN ({muni_agency_names$agency_num*})
  AND year = 2021
  ",
  .con = ptaxsim_db_conn
  )
)

muni_tax_codes <- muni_tax_codes %>% left_join(muni_agency_names)

```


```{r}
# There are 1,864,594 pins taxed by Cook County in 2021.
cook_pins <- DBI::dbGetQuery(
  ptaxsim_db_conn,
  glue_sql(
  "SELECT DISTINCT pin, class, tax_code_num
  FROM pin
  WHERE tax_code_num IN ({cook_tax_codes$tax_code_num*})
  AND year = 2021
  ",
  .con = ptaxsim_db_conn
))



# finds all pins within a municipality
pin_data <- lookup_pin(2021, cook_pins$pin) %>%
  left_join(cook_pins, by = c("pin", "class")) 


# use the property class to make the major property types
# joins the class_dict file to the pin_data classes
pin_data <- pin_data %>%
  #select(-c(assessment_level:reporting_group, class_desc:max_size)) %>%
  left_join(class_dict, by = c("class" = "class_code"))

pin_data <- pin_data %>% 
  left_join(muni_tax_codes)

# has exemption types and amount that went to every pin in Cook County
# write_csv(pin_data, "./Output/3_Exemption_Details_output-all_cook_pin_exemptions_2021_actual.csv")
```


# Cook Quartiles

There are 346,684 Class 203 properties in Cook county.

```{r}

class203 <- pin_data %>% 
  filter(class == "203") 

class203 %>%
  ggplot( aes(y=av)) +
    geom_boxplot()  +
  theme_classic()+
  coord_flip()+
    labs(title = "Cook County Class 203 Distribution of AV", y = "Assessed Value ($)", x="") +
  scale_y_continuous(label = scales::dollar)


# Quartiles
quantile(class203$av)


# Deciles
quantile(class203$av, probs = c(0, .1, .2, .3, .4, .5, .6, .7, .8, .9, 1))
```

Cook County Quartiles

0%   25%     50%     75%     100%    
0    13,017  18,527  24,978  433,463     




## Quartiles by Municipality

```{r}
class203 %>%
  filter(agency_name %in% c("CITY OF CHICAGO", "VILLAGE OF DOLTON", "VILLAGE OF GLENCOE", "VILLAGE OF OAK PARK")) %>%
  ggplot( aes(y=av)) +
  geom_boxplot() +
  coord_flip() +
  theme_bw() + 
  labs(title = "Class 203 Distribution of AV", y = "Assessed Value ($)", x= "" ) +
  scale_y_continuous(label = scales::dollar) +
  facet_wrap(~agency_name, nrow=4)
```

Municipalities are ordered by median AV for Class 203 properties.

```{r}
q = c(.25, .5, .75)

class203 %>%
  left_join(nicknames) %>%
  group_by(clean_name) %>%
  summarize(count_203pins = n(), 
            min = min(av),
            quant25 = quantile(av, probs = q[1]), 
            quant50 = quantile(av, probs = q[2]),
            quant75 = quantile(av, probs = q[3]),
            max = max(av)) %>% 
  arrange( desc( quant50)) 


table <- class203 %>%
  left_join(nicknames) %>%
  group_by(clean_name) %>%
  summarize(count_203pins = n(), 
            min = min(av),
            quant25 = quantile(av, probs = q[1]), 
            quant50 = quantile(av, probs = q[2]),
            quant75 = quantile(av, probs = q[3]),
            max = max(av)) %>% 
  arrange( desc( quant50))


write_csv(table, "meetingdata_class203.csv")
  

```


## Class 205 Quartiles

Ordered highest to lowest median AV.

```{r}
pin_data %>% 
  filter(class == "205") %>% 
  left_join(nicknames) %>%
  group_by(clean_name) %>%
  summarize(count_205pins = n(), 
            min = min(av),
            quant25 = quantile(av, probs = q[1]), 
            quant50 = quantile(av, probs = q[2]),
            quant75 = quantile(av, probs = q[3]),
            max = max(av)) %>% 
  arrange( desc( quant50)) 
```


```{r}
pin_data %>% 
  filter(class == "205") %>% 
  filter(agency_name %in% c("CITY OF CHICAGO", "VILLAGE OF DOLTON", "VILLAGE OF GLENCOE", "VILLAGE OF OAK PARK")) %>% 
  ggplot( aes(y=av)) +
    geom_boxplot() +
  coord_flip() +
  theme_bw() + 
    labs(title = "Class 205 Distribution of AV", y = "Assessed Value ($)", x= "" ) + 
  facet_wrap(~agency_name, nrow=4)
```

