---
title: "Burden Shift from Incentive Properties" 
format: 
  html:
    df-print: paged
    code-fold: true
    code-download: true
    toc: true
    toc-location: left
    fig-cap-location: top
    fig-height: 10
---

**Preliminary Setup**

```{r setup, warning = FALSE, output = FALSE}

library(tidyverse)
library(ptaxsim)
library(DBI)
library(httr)
library(jsonlite)
library(glue)
library(sf)

knitr::opts_chunk$set(warning = FALSE, message = FALSE)


```

```{r}
#| code-fold: true

nicknames <- readxl::read_excel("./Necessary_Files/muni_shortnames.xlsx") 


class_dict <- read_csv("./Necessary_Files/class_dict_expanded.csv") %>% select(class_code, class_desc, Alea_cat, everything()) 


MuniLevel <- read_csv("./Output/ptaxsim_muni_level_2006-2021.csv") %>%
  filter(year == 2021) %>%
  left_join(nicknames) %>% 
  select(clean_name, cur_comp_muni_rate) %>%
  rename(cur_munilevel_rate = cur_comp_muni_rate)


MC_sums <- read_csv("./Output/ptaxsim_muni_MC_2006-2021.csv") %>% 
  filter(year == 2021) %>% 
  left_join(nicknames) 

tc_class <- read_csv("./Output/ptaxsim_TC_Class_summaries_2006-2021.csv") %>% 
  filter(year == 2021)

muni_class2022 <- read_csv("./Output/ptaxsim_muni_class_summaries_2006-2022.csv") %>% 
  filter(year == 2022)

eqfact22 <- 2.9237 # 2022 CC equalization factor
eqfact21 <- 3.0027 # 2021 CC Equalization Factor
```

```{r include = FALSE}
incentive_sums <- MC_sums %>%
  left_join(MuniLevel) %>%
  mutate(
         incentive = ifelse(major_class_code %in% c("6A","6B", "6C", "7A","7B","7C","8"), "Incentive", "Non-Incentive"),
         incent_type = ifelse(major_class_code %in% c("6A","6B", "6C"), "Industrial", ifelse(major_class_code %in% c("7A","7B","7C", "8"), "Commercial", "Not Incentive Prop"))) %>%
  group_by(year, clean_name, incentive, cur_munilevel_rate) %>%
  summarize(av = sum(av),
            eav = sum(eav),
            pins_in_muni = sum(pins_in_muni), # all pins
            incent_pins = n(),
            final_tax_to_dist = sum(final_tax_to_dist),
            current_taxable_eav = sum(current_taxable_eav))%>%
  mutate(new_av = ifelse(incentive == "Incentive", av*2.5, av),
    new_taxable_eav = ifelse(incentive ==  "Incentive", current_taxable_eav * 2.5 , current_taxable_eav))

incentive_sums 

incentive_sums %>% 
  filter(incentive == "Incentive") %>% arrange(-incent_pins)


```


```{r startfromclasslevelsummaries}
muni_class2021 <- read_csv("./Output/ptaxsim_muni_class_summaries_2006-2022.csv") %>% 
  filter(year == 2021) %>% 
  left_join(class_dict, by = c("class" = "class_code"))

muni_class_AleaCats <- muni_class2021 %>%
  left_join(MuniLevel) %>%
  mutate(Alea_cat = ifelse(Alea_cat %in% c("Exempt", "Residential", "Other Residential", 
                                           "Owner Occupied", "Rental"), "Non-Incentive", Alea_cat)) %>% 
  group_by(clean_name, incent_prop, Alea_cat, cur_munilevel_rate) %>%
  summarize(av = sum(av),
            eav = sum(eav), # equalized AV 
            final_tax_to_dist = sum(final_tax_to_dist), # revenue collected by taxing districts
            final_tax_to_tif = sum(final_tax_to_tif),   # revenue collected from TIF increment
            current_taxable_eav = sum(current_taxable_eav),
            pins_in_muni = n(),
            all_exemptions = sum(all_exemptions),
            abatements = sum(exe_abate),
  ) %>%
  mutate(
    # approximation for if assessments went from 10% to 25%, similar to other commercial and industrial property in Cook County
    new_av = ifelse(incent_prop == "Incentive", av*2.5, av), 
    
    new_TEAV_noIncents = ifelse(incent_prop ==  "Incentive", current_taxable_eav * 2.5 , current_taxable_eav),
    
    new_TEAV_noExemps = current_taxable_eav + all_exemptions, # does not include abatements
    
    # amount of EAV from taxing an additiona 15% of the AV if incentive properties didn't exist
    forgone_EAV_incent = ifelse(incent_prop == "Incentive", new_TEAV_noIncents - (current_taxable_eav + all_exemptions), 0),
    
    forgone_TIF_EAV = final_tax_to_tif / cur_munilevel_rate  )     


alt_rates <- muni_class_AleaCats %>% 
  group_by(clean_name, cur_munilevel_rate) %>% 
  mutate(munilevy = sum(final_tax_to_dist),
         muni_exemptions = sum(all_exemptions), # all exe_ variables except exe_abate
         muni_abatements = sum(abatements),
         muni_forgoneTIF = sum(forgone_TIF_EAV),
         muni_forgone_EAV_incent = sum(forgone_EAV_incent),

         muni_current_TEAV = sum(current_taxable_eav),
         muni_TEAV_noExe = sum(new_TEAV_noExemps),
         muni_TEAV_noInc = sum(new_TEAV_noIncents),
         
         ) %>%
  ungroup() %>%
  mutate(
    # Absolute maximum TEAV: No Exemptions, no abatements, no TIFS, no Incentive properties
    # Commercial and industrial assessed at 25%
    muni_TEAV_max = muni_current_TEAV + muni_exemptions + muni_abatements + muni_forgoneTIF + muni_forgone_EAV_incent,
    
    muni_TEAV_neither = muni_current_TEAV + muni_exemptions + muni_forgone_EAV_incent,
    
    muni_rate_noExe = munilevy / muni_TEAV_noExe * 100,
    muni_rate_noInc = munilevy / muni_TEAV_noInc * 100,
    muni_rate_neither = munilevy / muni_TEAV_neither * 100, 
    muni_rate_noTIFs = munilevy / (muni_current_TEAV + muni_forgoneTIF) * 100,
    muni_rate_lowest = munilevy / muni_TEAV_max * 100)

alt_rates <- alt_rates %>% 
  mutate(change_noExe = cur_munilevel_rate - muni_rate_noExe,
         change_noInc = cur_munilevel_rate - muni_rate_noInc,
         change_neither = cur_munilevel_rate - muni_rate_neither,
         change_max = cur_munilevel_rate - muni_rate_lowest
         )
```


```{r}
#| label: tbl-munirate-hypotheticals
#| tbl-cap: "Hypothetical Composite Tax Rates"
#| column: page

tbl1 <- alt_rates %>% select(clean_name, cur_munilevel_rate, muni_rate_noExe, muni_rate_noInc, muni_rate_neither, muni_rate_noTIFs, muni_rate_lowest) %>% distinct() %>% 
    mutate(across(cur_munilevel_rate:muni_rate_lowest, round, digits = 2)) %>% as.data.frame()

tbl1

```


```{r}
#| label: tbl-muni-ratechange
#| tbl-cap: "Hypothetical Change in Composite Tax Rates"
#| column: page

tbl2 <- alt_rates %>% select(clean_name, change_noExe, change_noInc, change_neither, change_max) %>%
  distinct() %>%
  mutate(across(change_noExe:change_max, round, digits = 2)) %>% as.data.frame()

tbl2

```
```{r}
#| label: fig-pctincentivevalue
#| fig-cap: "Composite Tax Rate Change from recovering reduced AV of properties with incentive classification" 
#| fig-height: 5


library(sf)

muni_shp <- read_sf("https://gis.cookcountyil.gov/traditional/rest/services/politicalBoundary/MapServer/2/query?outFields=*&where=1%3D1&f=geojson")

tbl2 %>% 
  left_join(nicknames) %>%
  left_join(muni_shp, by = c("shpfile_name" = "MUNICIPALITY")) %>%

    ggplot(aes(fill = change_neither)) +
    geom_sf(aes(geometry = geometry), color = "black") +
  theme_void() + 
  theme(axis.ticks = element_blank(), axis.text = element_blank())+
scale_fill_steps2(
    high = "#420420", low = "black",
  # midpoint = median(transfered_taxes),
  limits = c(0,15.5),
                   show.limits=TRUE,
  nice.breaks=FALSE,
  na.value=NA,
                    n =4,
                       name = "Change in Composite Tax Rate\n(Percentage Points)",
)
```


```{r}
#| label: fig-incent-and-exempt-ratechange-map
#| fig-height: 5
#| layout-ncol: 2
#| column: page
#| fig-subcap:
#|      - "Change in composite tax rate from taxing incentive properties at 25% instead of 10%"
#|      - "Change in composite taxrate from taxing EAV that is current tax exempt due to the GHE exemption"

tbl2 %>% 
  left_join(nicknames) %>%
  left_join(muni_shp, by = c("shpfile_name" = "MUNICIPALITY")) %>%

    ggplot(aes(fill = change_noInc)) +
    geom_sf(aes(geometry = geometry), color = "black") +
  theme_void() + 
  theme(axis.ticks = element_blank(), axis.text = element_blank())+
scale_fill_steps2(
    high = "forestgreen",
 limits = c(0,7),
                   show.limits=TRUE,
  nice.breaks=FALSE,
  na.value=NA,
                    n =4,
                       name = "Change in Composite Tax Rate\n(Percentage Points)",)


tbl2 %>% 
  left_join(nicknames) %>%
  left_join(muni_shp, by = c("shpfile_name" = "MUNICIPALITY")) %>%

    ggplot(aes(fill = change_noExe)) +
    geom_sf(aes(geometry = geometry), color = "black") +
  theme_void() + 
  theme(axis.ticks = element_blank(), axis.text = element_blank())+
scale_fill_steps2(
    high = "purple4",
 limits = c(0,15),
                   show.limits=TRUE,
  nice.breaks=FALSE,
  na.value=NA,
                    n =4,
                       name = "Change in Composite Tax Rate\n(Percentage Points)",
        # labels = scales::percent
)
```


```{r exportXL, include=FALSE, eval = FALSE}
library(openxlsx)
list_for_tabs <- list("Alt Tax Rates" = tbl1, "Rate Change" = tbl2)

# write.xlsx(list_for_tabs, file = "./Output/datarequest_taxratechange_03112024.xlsx")
```

```{r commer_indust_incents, include = FALSE}
incentive_sums2 <- MC_sums %>%
  left_join(MuniLevel) %>%
  mutate(
         incentive = ifelse(major_class_code %in% c("6A","6B", "6C", "7A","7B","7C","8"), "Incentive", "Non-Incentive"),
         incent_type = ifelse(major_class_code %in% c("6A","6B", "6C"), "Industrial", ifelse(major_class_code %in% c("7A","7B","7C", "8"), "Commercial", "Not Incentive Prop"))) %>%
  group_by(clean_name, incent_type, cur_munilevel_rate) %>%
  summarize(av = sum(av),
            eav = sum(eav),
            pins_in_muni = sum(pins_in_muni),
            final_tax_to_dist = sum(final_tax_to_dist),
           # current_rate = mean(cur_comp_muni_rate),
            current_taxable_eav = sum(current_taxable_eav))%>%
  mutate(new_av = ifelse(incent_type != "Not Incentive Prop", av*2.5, av),
    new_taxable_eav = ifelse(incent_type !=  "Not Incentive Prop", current_taxable_eav * 2.5 , current_taxable_eav))

incentive_sums2 <- incentive_sums2 %>% 
  group_by(clean_name) %>% 
  mutate(munilevy = sum(final_tax_to_dist),
         cur_muni_taxable_eav = sum(current_taxable_eav),
         new_muni_taxable_eav = sum(new_taxable_eav)) %>%
  ungroup() %>%
  mutate(new_comp_rate = munilevy / new_muni_taxable_eav * 100)


burden2 <- incentive_sums2 %>% 
  mutate(group_taxes_hyp = new_taxable_eav * (new_comp_rate),
         group_taxes_cur = current_taxable_eav * cur_munilevel_rate,
         pct_eav = eav / cur_muni_taxable_eav) %>%
  mutate(
    pct_taxburden_current = group_taxes_cur / munilevy,
    pct_taxburden_no_incent = group_taxes_hyp / munilevy,
    burden_shift = round(pct_taxburden_current - pct_taxburden_no_incent, digits = 2 ),
    av_change_perPIN = ifelse(incent_type %in% c("Commercial", "Industrial"), (new_av - av)/pins_in_muni, NA))

burden2 %>% arrange(clean_name) %>% select(clean_name, incent_type, burden_shift)

# write_csv(burden2, "./Output/incentive_burdenshift_bygrouptype.csv")

```


```{r}
incentive_sums <- incentive_sums %>% 
  group_by(clean_name) %>% 
  mutate(munilevy = sum(final_tax_to_dist),
         cur_muni_taxable_eav = sum(current_taxable_eav),
         new_muni_taxable_eav = sum(new_taxable_eav)) %>%
  ungroup() %>%
  mutate(new_comp_rate = munilevy / new_muni_taxable_eav * 100)




burden <- incentive_sums %>% 
  mutate(group_taxes_hyp = new_taxable_eav * (new_comp_rate),
         group_taxes_cur = current_taxable_eav * cur_munilevel_rate,
         pct_eav = eav / cur_muni_taxable_eav) %>%
    mutate(rate_change = cur_munilevel_rate - new_comp_rate) %>%

  mutate(
    pct_taxburden_current = group_taxes_cur / munilevy,
    pct_taxburden_no_incent = group_taxes_hyp / munilevy,
    
    burden_shift = round(pct_taxburden_current - pct_taxburden_no_incent, digits = 2 ),
    av_change_perPIN = ifelse(incentive == "Incentive", (new_av - av)/pins_in_muni, NA))
```


```{r include = FALSE}
#| code-fold: true
#| column: screen
#| tbl-cap: "Incentive Properties (Combined) Tax Rates and Burden"

burden %>% 
  filter(incentive == "Incentive" & clean_name != "NA") %>%
  select(Municipality = clean_name, cur_munilevel_rate, new_comp_rate, pct_taxburden_current, pct_taxburden_no_incent) %>% 
  mutate_if(is.numeric, ~round(., 1))


# burden %>% write_csv("./Output/incentive_burden_shift.csv")



```

## Change in Composite Tax Rate 
```{r}

# as a dot graph ## 
# create order of dots
order <- burden %>%  
  as_tibble() %>% 
  filter(incentive == "Incentive") %>% 
  arrange( rate_change) %>%
  select(clean_name, cur_munilevel_rate, new_comp_rate)

# make dot graph
burden %>% 
  filter(incentive == "Incentive" & clean_name != "NA") %>%
  select(clean_name, cur_munilevel_rate, new_comp_rate, rate_change) %>% 
  pivot_longer(c("cur_munilevel_rate", "new_comp_rate"), 
               names_to = "type", values_to = "tax_rate") %>% 
  left_join(order) %>%
  ggplot(aes(x = tax_rate, y= reorder(clean_name, rate_change)))+
  geom_line(aes(group = clean_name))+ 
  geom_point(aes(color=type), size=3 )+
  theme_minimal() + 
  theme( 
    legend.title = element_blank(),
    plot.title.position = "plot",
    plot.background = element_rect(fill='transparent', color=NA) #transparent plot bg
  )+
  scale_color_brewer(palette="Paired", labels = c("Incentives", "No Incentives"), direction = 1)+
  
  labs(title = "Difference in Composite Tax Rate if Assessed at 25%",
       subtitle = "Ordered by Comp. Rate Change", x = "Composite Tax Rate (%)", y = "")
```

```{r}

# as a dot graph ## 
# create order of dots
order <- burden %>%  
  as_tibble() %>% 
  filter(incentive == "Incentive") %>% 
  arrange(cur_munilevel_rate) %>%
  select(clean_name, cur_munilevel_rate)

# make dot graph
burden %>% 
  filter(incentive == "Incentive" & clean_name != "NA") %>%
  select(clean_name, cur_munilevel_rate, new_comp_rate) %>% 
  pivot_longer(c("cur_munilevel_rate", "new_comp_rate"), 
               names_to = "type", values_to = "tax_rate") %>% 
  left_join(order) %>%
  ggplot(aes(x = tax_rate, y= reorder(clean_name, cur_munilevel_rate)))+
  geom_line(aes(group = clean_name))+ 
  geom_point(aes(color=type), size=3 )+
  theme_minimal() + 
  theme( 
    legend.title = element_blank(),
    plot.title.position = "plot",
    plot.background = element_rect(fill='transparent', color=NA) #transparent plot bg
  )+
  scale_color_brewer(palette="Paired", labels = c("Incentives", "No Incentives"), direction = 1)+
  
  labs(title = "Difference in Composite Tax Rate if Assessed at 25%",
       subtitle = "Ordered by Current Composite Tax Rate", x = "Composite Tax Rate (%)", y = "")
```


## Change in Tax Burden

```{r incentiveprops}

# as a dot graph ## 

order <- burden %>%  
  as_tibble() %>% 
  filter(incentive == "Incentive") %>% 
  arrange(pct_taxburden_current) %>%
  select(clean_name, pct_taxburden_current)

burden %>% 
  filter(incentive == "Incentive" & clean_name !="NA") %>%
  select(clean_name, pct_taxburden_current, pct_taxburden_no_incent) %>% 
  pivot_longer(c("pct_taxburden_current", "pct_taxburden_no_incent"), 
               names_to = "type", values_to = "tax_rate") %>% 
  left_join(order) %>%
  ggplot(aes(x = tax_rate, y= reorder(clean_name, pct_taxburden_current)))+
  
  geom_line(aes(group = clean_name))+ 
  geom_point(aes(color=type), size=3 )+
  theme_minimal() + 
  theme( 
    legend.title = element_blank(),
    plot.title.position = "plot",
    plot.background = element_rect(fill='transparent', color=NA) #transparent plot bg
  )+
  scale_color_brewer(palette="Paired", labels = c("Incentives", "No Incentives"), direction = 1)+
  
  labs(title = "Tax Burden for Incentive Properties if Assessed at 25%",
       subtitle = "Ordered by Current Tax Burden", x = "% of Levy Paid", y = "" , 
       caption = "")
```


```{r industrialburden}

# as a dot graph ## 

order <- burden2 %>%  
  as_tibble() %>% 
  filter(incent_type == "Industrial") %>% 
  arrange(pct_taxburden_current) %>%
  select(clean_name, pct_taxburden_current)

burden2 %>% 
  filter(incent_type == "Industrial" & clean_name !="NA") %>%
  select(clean_name, pct_taxburden_current, pct_taxburden_no_incent) %>% 
  pivot_longer(c("pct_taxburden_current", "pct_taxburden_no_incent"), 
               names_to = "type", values_to = "tax_rate") %>% 
  left_join(order) %>%
  ggplot(aes(x = tax_rate, y= reorder(clean_name, pct_taxburden_current)))+
  
  geom_line(aes(group = clean_name))+ 
  geom_point(aes(color=type), size=3 )+
  theme_minimal() + 
  theme( 
    legend.title = element_blank(),
    plot.title.position = "plot",
    plot.background = element_rect(fill='transparent', color=NA) #transparent plot bg
  )+
  scale_color_brewer(palette="Accent", labels = c("Incentives", "No Incentives"), direction = 1)+
  
  labs(title = "Tax Burden for Industrial Properties if Assessed at 25%",
       subtitle = "Ordered by Current Tax Burden", x = "% of Levy Paid", y = "" , 
       caption = "")
```


```{r commercialburden}

# as a dot graph ## 

order <- burden2 %>%  
  as_tibble() %>% 
  filter(incent_type == "Commercial") %>% 
  arrange(pct_taxburden_current) %>%
  select(clean_name, pct_taxburden_current)

burden2 %>% 
  filter(incent_type == "Commercial" & clean_name !="NA") %>%
  select(clean_name, pct_taxburden_current, pct_taxburden_no_incent) %>% 
  pivot_longer(c("pct_taxburden_current", "pct_taxburden_no_incent"), 
               names_to = "type", values_to = "tax_rate") %>% 
  left_join(order) %>%
  ggplot(aes(x = tax_rate, y= reorder(clean_name, pct_taxburden_current)))+
  
  geom_line(aes(group = clean_name))+ 
  geom_point(aes(color=type), size=3 )+
  theme_minimal() + 
  theme( 
    legend.title = element_blank(),
    plot.title.position = "plot",
    plot.background = element_rect(fill='transparent', color=NA) #transparent plot bg
  )+
  scale_x_continuous(limits = c(0, 60)) + 
  scale_color_brewer(palette = "Dark2", labels = c("Incentives", "No Incentives"), direction = 1)+
  
  labs(title = "Tax Burden for Commercial Properties if Assessed at 25%",
       subtitle = "Ordered by Current Tax Burden", x = "% of Levy Paid", y = "" , 
       caption = "")
```
