---
title: "Pin table"
format: html
---

|  |  |  |  |  |
|-----------|-------------|-----------|----------------|----------------|
|  | Source: <https://www.cookcountypropertyinfo.com/> | Source: <https://www.cookcountyassessor.com/address-search> |  |  |
| **PIN** | **Treasurer Exemps.** | **CCAO Exemps.** | **Municipality** | **FMV** |
|  |  |  |  |  |
| 16063130270000 | GHE; Dis. Vet | GHE | Oak Park | \$940,000 |
|  |  |  |  |  |
| 19362220200000 | GHE; Dis. Vet. | GHE | Chicago | \$140,000 |
|  |  |  |  |  |
| 13231160160000 | GHE; Dis. Vet | GHE | Chicago | \$670,000 |
|  |  |  |  |  |
| 27181040410000 | GHE; Dis. Vet | GHE | Orland Park | \$700,000 |
|  |  |  |  |  |
| 05204080120000 | GHE; Dis. Vet | GHE | Winnetka | \$872,230 |
|  |  |  |  |  |
| 05332030150000 | GHE; Senior; Dis. Vet | GHE; Senior | Wilmette | \$875,000 |
|  |  |  |  |  |
| 02214040310000 | GHE; Dis. Vet | GHE | Palatine | \$860,000 |
|  |  |  |  |  |
| 31274090020000 | GHE; Dis. Vet | GHE | Richton Park | \$140,000 |
|  |  |  |  |  |
| 20302010100000 | GHE; Senior; Dis. Vet | GHE; Senior | Chicago | \$250,000 |
|  |  |  |  |  |
| 06134050330000 | GHE; Dis. Vet | GHE | Streamwood | \$220,000 |
|  |  |  |  |  |
| 18173030070000 | GHE; Senior; Dis. Vet. | GHE | La Grange | \$890,010 |
|  |  |  |  |  |
| 10244020370000 | GHE; Dis. Vet. | GHE | Evanston | \$800,000 |
|  |  |  |  |  |
| 22241070050000 | GHE; Dis. Vet | GHE | Lemont | \$810,000 |
|  |  |  |  |  |
| 27291170100000 | GHE; Dis. Vet | GHE | Orland Park | \$880,000 |
|  |  |  |  |  |
| 10113030300000 | GHE; Dis. Vet | GHE | Evanston | \$779,240 |
|  |  |  |  |  |
| 04063050210000 | GHE; Dis. Vet | GHE | Northbrook | \$730,010 |
|  |  |  |  |  |
| 22331180040000 | GHE; Dis. Vet | GHE | Lemont | \$700,000 |
|  |  |  |  |  |
| 09354170170000 | GHE; Senior; Dis. Vet. | GHE; Senior | Park Ridge | \$700,000 |
|  |  |  |  |  |
| 14302080030000 | GHE; Dis. Vet. | GHE | Chicago | \$670,010 |
|  |  |  |  |  |
| 01022060290000 | GHE; Dis. Vet. | GHE | Barrington | \$510,000 |
|  |  |  |  |  |
| 17202330810000 | GHE; Dis. Vet. | GHE | Chicago | \$500,000 |
|  |  |  |  |  |
| 15344030260000 | GHE; Dis. Vet. | GHE | Brookfield | \$500,310 (Treasurer); \$486,830 (CCAO) |
|  |  |  |  |  |
| 03082070270000 | GHE; Senior; Dis. Vet. | GHE; Senior | Arlington Heights | \$500,000 |
|  |  |  |  |  |
| 06202050020000 | GHE; Dis. Vet. | GHE | Elgin | \$410,000 |
|  |  |  |  |  |
| 02173070020000 | GHE; Dis. Vet. | GHE | Inverness | \$403,620 |
|  |  |  |  |  |
| 13053220250000 | GHE; Senior; Dis. Vet. | GHE; Senior | Chicago | \$430,000 |
|  |  |  |  |  |
| 04251080120000 | GHE; Senior; Dis. Vet. | GHE; Senior | Glenview | \$455,410 (Treasurer); \$412,930 (CCAO) |
|  |  |  |  |  |
| 18172080200000 | GHE; Senior; Dis. Vet. | GHE; Senior | La Grange | \$410,000 |
|  |  |  |  |  |
