---
title: "Homestead Exemption Use in Cook County"
---

Taxcode Level

```{r taxcode_level, echo=FALSE}

### NEED NEW DATA SOURCE ###

#exemptions_by_class_per_TC <- read_csv("3_Exemption_Details_output-Cook_Exemps_byClassandTaxcode.csv")


cooktotals <- exemptions_by_class_per_TC %>%
  summarize(
    av = sum(av, na.rm = TRUE),
    eav = sum(eav, na.rm = TRUE),
    total_exempt_eav = sum(
      exe_homeowner + exe_senior + exe_freeze + exe_longtime_homeowner +
        exe_disabled + exe_vet_returning + exe_vet_dis + exe_abate,
      na.rm = TRUE
    ),
    homeowners_exemption = sum(exe_homeowner),
    senior_exemption = sum(exe_senior, na.rm = TRUE),
    freeze_exemption = sum(exe_freeze, na.rm = TRUE),
    pin_count = n()
  ) %>%
  pivot_longer(cols = av:pin_count,
               names_to = "Variables",
               values_to = "Cook County Totals")

munitotals <- exemptions_by_class_per_TC %>%
  filter(tax_code_num %in% muni_tax_codes$tax_code_num) %>%
  summarize(
    av = sum(av, na.rm = TRUE),
    eav = sum(eav, na.rm = TRUE),
    total_exempt_eav = sum(
      exe_homeowner + exe_senior + exe_freeze + exe_longtime_homeowner +
        exe_disabled + exe_vet_returning + exe_vet_dis + exe_abate,
      na.rm = TRUE
    ),
    homeowners_exemption = sum(exe_homeowner),
    senior_exemption = sum(exe_senior, na.rm = TRUE),
    freeze_exemption = sum(exe_freeze, na.rm = TRUE),
    pin_count = n()
  ) %>%
  pivot_longer(cols = av:pin_count,
               names_to = "Variables",
               values_to = "Municipality Totals")


total_exemptions <- left_join(cooktotals, munitotals)
total_exemptions

```

At the municipal level:

``` {r exemptiontype-permuni, include = FALSE}

exemptype_totals_permuni <- exemptions_by_class_per_TC %>% 
  mutate(tax_code_num = as.character(tax_code_num)) %>%
  left_join(muni_tax_codes) %>%
  left_join(muni_agency_names) %>%
  filter(tax_code_num %in% muni_tax_codes$tax_code_num)%>%
  group_by(agency_num, agency_name) %>%
  summarize(av = sum(av, na.rm = TRUE),
            eav=sum(eav, na.rm=TRUE),
            total_exempt_eav_inMuni = sum(exe_homeowner + exe_senior + exe_freeze + exe_longtime_homeowner + 
                         exe_disabled + exe_vet_returning + exe_vet_dis + exe_abate, na.rm=TRUE),
            exe_homeowner = sum(exe_homeowner, na.rm=TRUE),
            exe_senior = sum(exe_senior, na.rm=TRUE),
            exe_freeze = sum(exe_freeze, na.rm=TRUE),
            exe_longtime_homeowner = sum(exe_longtime_homeowner, na.rm=TRUE),
            exe_disabled = sum(exe_disabled, na.rm=TRUE),
            exe_vet_returning = sum(exe_vet_returning, na.rm=TRUE),
            exe_vet_dis = sum(exe_vet_dis, na.rm=TRUE),
            exe_abate = sum(exe_abate, na.rm=TRUE),
            muni_pin_count = n())

```