# Background Information {#sec-background-info .unnumbered}

---
format:
  html:
    code-fold: false
    code-tools: true
    code-overflow: wrap
---

::: {#disclaimer .callout-warning appearance="simple" icon="false"}
# Disclaimer

*The following materials are a work in progress based on property tax data released by the Cook County Assessor's Office (CCAO) and other publicly available data sources. Much of the incorporated data and analysis was prepared, in part, for Cook County's Property Tax Working Group. This data and analysis accompanies and supplements information in \[White Paper and Addendum\], available through the Cook County Assessor's Office.*

*We are especially indebted to Dan Snow, Rob Ross, and Mike Wu at CCAO for the development and release of PTAXSIM, a package in the R programming language which provides the public with a trove of historical property tax data, without which this analysis would not be possible.*

*We would also like to thank Professors Merriman, Weber, Carroll, and Drucker from UIC's College of Urban Planning and Public Policy for their support as well as the Chicago Metropolitan Agency for Planning (CMAP) for providing supplemental and background analysis.*:::

All data was originally posted by the Cook County Assessor's Office (CCAO).

Tax data for Cook County was gathered using CCAO's `ptaxsim` package and corresponding database.

All summarizing of data was done by Research Assistants working for the Government Finance Research Center at the University of Illinois Chicago.

If ignoring TIFs, the residential share of EAV is:

$$
ResidentrialShare = \frac{TaxableEAV_{residential} - ExemptEAV_{residential}} {TaxableEAV}
$$

$$
ResidentialShare = \frac{1-\lambda}{1-\lambda-\psi}
$$

$$
TaxableBase = AV_{equalized} - TIFincrement - EAV_{exempt} 
$$

$$
TIFincrement = AV_{equalized} - EAV_{frozen}
$$

The aggregate, or composite, tax rate is the sum of the individual taxing agency tax rates, or $\sum(rate_{agency})$, for all taxing agencies that tax a location. Each unique combination of taxing agencies is assigned a tax code by the assessor's office.

```{r eval=FALSE, include = FALSE}

## labels for summary tables
"TIF Increment Post-Exe" = scales::comma(final_tax_to_tif/composite_tax_rate),
    "Taxable EAV outside TIF, Post-Exe" = final_tax_to_dist/composite_tax_rate,
    "EAV in TIF Post-Exe" = (EAV_post_exemptions-`EAV outside TIF Post-Exe`),
     
    
    "Total Revenue Pre-Exe" = scales::dollar(tax_amt_pre_exe),
    "Total Revenue Post-Exe" = scales::dollar(tax_amt_post_exe),
    
    "District Rev Post-Exe" = scales::dollar(final_tax_to_dist),
    "TIF Rev Post-Exe" = scales::dollar(final_tax_to_tif),
    
    "District Tax Share Post-Exe" = scales::percent(dist_tax_share),
    # EAV in TIF pre-exe will be off becase EAV pre-exemptions will be off. 
   # "EAV in TIF Pre-Exe" = (EAV_pre_exemptions-`EAV outside TIF Post-Exe`),
   "Naive Savings" = scales::dollar(tax_amt_exe),
```


# Cook County's Property Tax Working Group

In \[XXX\], various Cook County government agencies agreed to something something something. The County engaged UIC and CMAP to undertake this study, which to-date has produced two comprehensive studies on exemptions.

In a White Paper released \[xxx\], and addendum released \[xxxx\], the Cook County Property Tax Working Group was presented with several conclusions from UIC's analysis of historical property tax data to measure the effect of exemptions on taxpayers' individual tax burdens as well as the fairness and equity of Cook County's property tax system overall.

Nevertheless, a certain amount of nuance was necessarily omitted from those reports: nuance we hope to supply here.

# Summary of Findings

UIC's research led to several main findings:

1.  While historical records provide clear reasons for the adoption of homeowner exemptions as a policy tool, current stakeholders throughout Cook County government cannot agree on the public purpose of homestead exemptions, a problem that flows through to properly acknowledging relevant costs, benefits, and stakeholders. Indeed, given divergent policy goals by different stakeholders, any construct of "effectiveness" would be challenging to measure.

2.  Cook County's property tax system allocates revenue to local governments based on each property owners' share of that jurisdiction's total tax base.

3.  CC's system of dividing the levy among property owners creates a "zero-sum" game where one taxpayer's bill must necessarily increase for another taxpayer's bill to decrease.

4.  Homeowner exemptions, designed to provide tax release to certain classes of homeowners, decrease property tax bills through a flat reduction in the taxpayer's contribution to the tax base in EAV.

5.  Exemptions also reduce the tax base, thereby driving tax rates up for all taxpayers (even those that receive exemptions). This push-pull effect causes the true amount of tax liability reduction to be sometimes significantly lower than suggested by government tax bills.

6.  Exemptions are theoretically and practically progressive, bringing greater tax relief to those with the lowest ability to pay (as imperfectly measured by their property's value).

7.  Anomalous outcomes can occur due to Cook County's socio-economic homogeneity. A handful of taxpayers would benefit more from exemptions' elimination (and the resulting decrease in tax rate) than from the exemption itself.

8.  There is no obvious solution to the detrimental effects of exemptions that are endogenous to the property tax system. Any "fix" must come from other revenue.

We have also appended an explanation of our data sources and how we prepared that data for analysis as well as a mathematical appendix of tedious equations.
