---
title: "Outline"
format: html
editor: visual
---

## Front Page / Background Page

\[\[Summary Tables of rate and Burden shifts by Muni\]\]

\[\[Link to Resources - PTAXSIM, Assessor's class codes, other "good" resources\]\]

\[\[disclaimer\]\]

\[\[Site Guide\]\]

# Whitepaper: Use of Exemptions

\[\[By PIN - how many pins get each type of exemptions, by EAV\]\]

methodology note - we used EAV, not FMV

-   MVH question - how many people get all exemptions or multiple exemptions

\[\[distribution of reduction in EAV?\]\]

## Tax Effects of Homestead Exemptions

### Rates

-   website table mostly done?

### Burden Shift

-   website table mostly done?

    \[\[direct and indirect stuff. Used bar graphs, use just a table? everything doesn't need a visualization\]\]

### Median Tax Payer

\[\[all munis\]\]

### What drives these things?

\[\[no idea what goes here\]\]

## Miscellaneous

### Zero dollar tax bills

### Paying for Alternatives

## Additional Background

### tax codes as unit of analyisis

And intra-muni-variation?

\[\[table of range of tax rates with municipalities\]\]

\[\[tax code level maps\]\]

### TIFs

Connection with exemptions

Amount of exempt EAV within TIF

-   assumes exempt eav gets added to taxable value for the taxing districts, not the TIFs increment above the frozen eav.

-   Essentially changing frozen eav when adding exempt eav back to tax base.

### Effect of Covid Factor on Analysis

\[\[What is the COVID factor\]\]

\[\[Potential impacts it could have on findings\]\]

## Time Trends?

Avg tax bill over time? Don't really have this done anywhere

## Appendix

### Methodology

"One we wrote before is not enough" - MVH

2.  Get and prepare Data?

### Data Acquisition and Cleaning

### 

## 
